"""per-model usage on scores and assessments

Revision ID: 51f2a28e7c12
Revises: 59ca173046ca
Create Date: 2026-07-11 17:07:41.434171
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '51f2a28e7c12'
down_revision: Union[str, None] = '59ca173046ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('turn_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn_scores', schema=None) as batch_op:
        batch_op.drop_column('output_tokens')
        batch_op.drop_column('input_tokens')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('output_tokens')
        batch_op.drop_column('input_tokens')

    # ### end Alembic commands ###
