"""pronunciation columns

Revision ID: b6f6128fad41
Revises: 51f2a28e7c12
Create Date: 2026-07-11 22:47:10.925897
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b6f6128fad41'
down_revision: Union[str, None] = '51f2a28e7c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronunciation', sa.Float(), nullable=True))

    with op.batch_alter_table('turn_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronunciation', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn_scores', schema=None) as batch_op:
        batch_op.drop_column('pronunciation')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('pronunciation')

    # ### end Alembic commands ###
